### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [denis-shvetcov/java#1]
1. - [x] Вместо создания пустой `HashMap` и последующего вызова `putAll` лучше сразу передавать `Map` для копирования в конструктор.
2. - [ ] Нельзя сделать `addToInversed` через `getOrDefault`, потому что `getOrDefault` только возвращает значение по умолчанию, если ключ не найден, но не кладёт его в `Map`. Для достижения желаемого результата вместо него нужно использовать метод `computeIfAbsent`.
3. - [ ] И `remove` и `replace` возвращают значение, которое хранилось в `Map` до вызова, так что не нужно отдельно делать `get` перед их вызовом, можно использовать возвращаемое значение этих функций.
4. - [x] Зачем в методах `getPeople` Вы делаете копию полученной `Map`?
5. - [x] Если Вам не нужны ключи, то можно итерироваться по `values()`.
6. - [x] Во втором методе `getPeople` Вы ищете нужный номер дома перебором, а не прямым поиском по ключу.
7. - [x] В тесте для `getPeople` нужно сравнивать так же через `assertEquals`, так как `containsAll` проверит только то, что не вернётся ничего лишнего (оно вернёт `true` даже на пустом множестве)

**Comment by denis-shvetcov** [comment]
Я исправил замечания. Сомневаюсь, что правильно понял насчет replace и
remove, но все-таки что-то сделал.

ср, 19 февр. 2020 г. в 16:10, Maxim Petrov <notifications@github.com>:

**Comment by maximpetrov** [comment]
1. - [ ] Почему Вы просто не сделали цепочку из двух вызовов `computeIfAbsent` подряд?
2. - [ ] `remove` и `replace` возвращают то же самое, что и `get`, поэтому я предложил Вам вызывать их сразу вместо `get`.
3. - [ ] А вот копию `Set` во втором `getPeople` как раз стоило бы сделать, чтобы никто случайно не сломал Ваш `inversedbook`, поменяв этот `Set`.
4. - [ ] Кстати, `inversedbook` должен называться `inversedBook`.

**Comment by denis-shvetcov** [comment]
1. У меня первоначально по какой-то причине это не получилось, сейчас работает.
2. Исправил методы.
3. Не понял про поломку inversedBook. Решил создать Set и передать в конструктор результат нахождения нужного Set'a по ключу, IDEA предложила добавить создание Set'a в return.
4. Заменено.
